modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="land_of_the_lost"
version="0.0.1"
displayName="Land of the Lost"
credits="Recipes and resources for Land of the lost modpack"
displayURL="https://www.curseforge.com/members/raziel23x/projects"
logoFile="logo.png"
authors="raziel23x, MCreator"

[[dependencies.land_of_the_lost]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



